### ISSUE TITLE
Licence type

### ISSUE THREAD

**Issue by lordrak007** [zacateras/sddl-parser#1]
Hi,
could you choose licence for using your code please?
Thanks
Lordrak

**Comment by zacateras** [comment]
@lordrak007 which one do you recommend? which one do you prefer?

**Comment by lordrak007** [comment]
It depends what do you preffer  :) May be MIT licence? It is in simple words permissive.
Do you plan extend parser to build sddl string from Acl which is created programmatically?
As i show you code rebuild parsed data but there is not option to add new  Ace or modiby ace.

**Comment by zacateras** [comment]
I do not have such plans until such feature is for some reason needed. However if you need extending the code with modification features please submit a PR. If you need a help with extending then we can proceed with other issues :).
