### ISSUE TITLE
compiled only DLL

### ISSUE THREAD

**Issue by johnjohnsp1** [zacateras/sddl-parser#17]
Hello, compiled the code but once done i have no exe:

1>------ Rebuild All started: Project: Sddl.Parser, Configuration: Debug Any CPU ------
1>C:\temp\sddl-parser\src\Sddl.Parser\Ace.cs(8,18,8,21): warning CS0659: 'Ace' overrides Object.Equals(object o) but does not override Object.GetHashCode()
1>C:\temp\sddl-parser\src\Sddl.Parser\Ace.cs(8,18,8,21): warning CS0661: 'Ace' defines operator == or operator != but does not override Object.GetHashCode()
1>C:\temp\sddl-parser\src\Sddl.Parser\Acl.cs(7,18,7,21): warning CS0659: 'Acl' overrides Object.Equals(object o) but does not override Object.GetHashCode()
1>C:\temp\sddl-parser\src\Sddl.Parser\Acl.cs(7,18,7,21): warning CS0661: 'Acl' defines operator == or operator != but does not override Object.GetHashCode()
1>C:\temp\sddl-parser\src\Sddl.Parser\Sddl.cs(7,18,7,22): warning CS0659: 'Sddl' overrides Object.Equals(object o) but does not override Object.GetHashCode()
1>C:\temp\sddl-parser\src\Sddl.Parser\Sddl.cs(7,18,7,22): warning CS0661: 'Sddl' defines operator == or operator != but does not override Object.GetHashCode()
1>C:\temp\sddl-parser\src\Sddl.Parser\Sid.cs(5,18,5,21): warning CS0659: 'Sid' overrides Object.Equals(object o) but does not override Object.GetHashCode()
1>C:\temp\sddl-parser\src\Sddl.Parser\Sid.cs(5,18,5,21): warning CS0661: 'Sid' defines operator == or operator != but does not override Object.GetHashCode()
1>Sddl.Parser -> C:\temp\sddl-parser\src\Sddl.Parser\bin\Debug\netstandard2.0\Sddl.Parser.dll
1>Done building project "Sddl.Parser.csproj".
2>------ Rebuild All started: Project: Sddl.Parser.Console, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: Sddl.Parser.Tests, Configuration: Debug Any CPU ------
2>Sddl.Parser.Console -> C:\temp\sddl-parser\src\Sddl.Parser.Console\bin\Debug\netcoreapp2.1\Sddl.Parser.Console.dll
3>Sddl.Parser.Tests -> C:\temp\sddl-parser\test\Sddl.Parser.Tests\bin\Debug\netcoreapp2.1\Sddl.Parser.Tests.dll

using  Vstudio2019 with all packaged required updated
any ideas ? 
i see the output in property group of sddl-parser-console.csproj as exe but seems that parameters is ignored

anything i do wrong ?

thanks

**Comment by zacateras** [comment]
@johnjohnsp1 this is rather configuration dependent thing. Hope this link helps: https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio

**Comment by johnjohnsp1** [comment]
Thanks for the reply, all fine.
